name: Browser compatibility (Firefox and Safari)

on:
  schedule:
    # At the end of every day
    - cron: '0 0 * * *'
  workflow_dispatch:
    inputs:
      repo:
        description: 'vite repository to use'
        required: true
        type: string
        default: 'tinker7th/test-ci'
      branchName:
        description: 'vite branch to use'
        required: true
        type: string
        default: 'main'
jobs:
  main-test:
    name: Playground E2E test
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        browsers: [firefox, webkit]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: ${{ inputs.repo }}
          ref: ${{ inputs.branchName }}
      - uses: pnpm/action-setup@v2
        with:
          version: 7.9.5
      - uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Install playwright browsers
        run: npx playwright install ${{ matrix.browsers }}
